### ISSUE TITLE
Не работает phx

### ISSUE THREAD

**Issue by SergeyMiracle** [webber12/evobabel-0.2#20]
PHx не отрабатывает теги `[*content*]` при включенном evoBabelPlaceholder

**Comment by webber12** [comment]
А при выключенном отрабатывает нормально? Я уже просто сто лет не пользовался phx - попробуйте поменять местами порядок исполнения - т.к. они оба висят на одном событии.

**Comment by SergeyMiracle** [comment]
При выключенном результат появляется, при включенном просто пустота.

**Comment by webber12** [comment]
Странно, поставил только что специально phx - если он по порядку следует за evoBabelPlaceholder в порядке следования плагинов - то нормально все показывает. Что за модификаторы используете? Доступ к сайту есть?

**Comment by SergeyMiracle** [comment]
Стукни в скайп я дам доступ - sergeymiracle - может я реально где-то плуга поймал :)

**Comment by webber12** [comment]
кидай в почту - web-ber12@yandex.ru
