### ISSUE TITLE
Необъявленная переменная в модуле

### ISSUE THREAD

**Issue by 64j** [webber12/evobabel-0.2#29]
Переменная $lang не существует в модуле, но есть $langs.

https://github.com/webber12/evobabel-0.2/blob/master/install/assets/modules/module.Lexicon.tpl#L51
```$lang```
заменить на
```$langs```

**Comment by webber12** [comment]
Ох уж эти необъявленные переменные в php7 )
Поправил - https://github.com/webber12/evobabel-0.2/commit/3d2f75ae4492e075242ba07623f501d379529125
