### ISSUE TITLE
Необъявленные переменные.

### ISSUE THREAD

**Issue by 64j** [webber12/evobabel-0.2#30]
В классе 
https://github.com/webber12/evobabel-0.2/blob/master/assets/snippets/evoBabel/evoBabel.class.php

https://github.com/webber12/evobabel-0.2/blob/master/assets/snippets/evoBabel/evoBabel.class.php#L197
добавить в начало
```$langs = array();```

https://github.com/webber12/evobabel-0.2/blob/master/assets/snippets/evoBabel/evoBabel.class.php#L210
добавить в начало
```$langs = array();```

https://github.com/webber12/evobabel-0.2/blob/master/assets/snippets/evoBabel/evoBabel.class.php#L250
```return $res[0];``` => ```return isset($res[0]) ? $res[0] : '';```

**Comment by webber12** [comment]
https://github.com/webber12/evobabel-0.2/commit/1033cd659e4f7be95e2cfc9a8ab514c880e292d7  готово
